### ISSUE TITLE
It would be nice if the webui showed projects with no issues

### ISSUE THREAD

**Issue by claudijd** [BuffaloWill/gumbler#16]
I would be cool if the UI still showed all the projects that were analyzed, even if there were no results.  I find it sort of confusing that a analyze a project and it doesn't show up on the web ui.  It makes it hard to distinguish the difference between a failed analysis and no findings analysis.

**Comment by BuffaloWill** [comment]
Agreed 🕶. Just landed a commit for this. I added a new projects collection to the db so any analysis moving forward will keep track of 0 result projects (or all projects for that matter).

For an analysis you have done in the past you will need to upload a json file of results into the db to see the project. This can be done on the entire directory containing json files:
```
python gumbler -j output
```
or with a single json file:
```
python gumbler -j output/my_project.json
```

Also there is a new findings count feature. To update the db click on "Update Project Findings Count" in /list or /orgs. The first time you start the webserver it will look like there are no projects, but this just needs to be run.

**Comment by claudijd** [comment]
Baller.
